lista_palavras = [
    "atletico mineiro",
    "Palmeiras",
    "Fortaleza",
    "Red Bull Bragantino",
    "Flamengo",
    "Athletico Paranaense",
    "Atletico Goianiense",
    "Ceara",
    "Internacional",
    "Santos",
    "Corinthians",
    "Juventude",
    "Bahia",
    "Sao Paulo",
    "Fluminense",
    "Cuiaba",
    "Sport",
    "America Mineiro",
    "Gremio",
    "Chapecoense",
    "Avaí",
    "Botafogo",
    "Brasil de Pelotas",
    "Brusque",
    "Confiança",
    "Coritiba",
    "crb",
    "Cruzeiro",
    "csa",
    "Goias",
    "Guarani",
    "Londrina",
    "Náutico",
    "Operário",
    "Ponte Preta",
    "Remo",
    "Sampaio Correa",
    "Vasco da Gama",
    "Vila Nova",
    "Vitoria",
]
